### ISSUE TITLE
Discriminator statistics are not storing on the tensor board 

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#12]
In this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/network_models/discriminator.py#L38) you have added **tf.summary.scalar('discriminator', loss)** to the summary. But when I observe the tensorboard there are only ppo losses. I think there's a problem with this  [line](https://github.com/uidilr/gail_ppo_tf/blob/master/algo/ppo.py#L76). Here the tf.summary.merge_all() only merges ppo scalars.

**Comment by uidilr** [comment]
Thanks for point it out!
I will fix it in this weekend.
