### ISSUE TITLE
Where do you use the get_grad function ?

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#14]
In this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/algo/ppo.py#L109) inside the ppo.py you have implemented get_grad. But seems like you didn't use it. Is there any reason?

**Comment by uidilr** [comment]
I have used it for debugging.
#13 seems okay for debugging too, but I think it is too complicated if it's only for debugging.
