### ISSUE TITLE
Is there any way we can encourage the exploration strategy of the agent ? 

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#16]
I've heard by adding entropy to the loss we can encourage the RL agent to explore more. I tried to train this PPO-Gail method with high dim inputs.  At the beginning of training, almost all actions have the same probability. After some training, some actions get higher probability (in the direction of getting more rewards), and entropy is reduced over time. 

If I want this how can I add entropy?

**Comment by uidilr** [comment]
You can change the value of coefficient for entropy.
