### ISSUE TITLE
How did you implement proximal Policy Gradients in run_ppo.py?

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#2]
Also I would like to know what is **self.gaes** in ppo.py file.

**Comment by uidilr** [comment]
Hi @shamanez, thanks for asking.
**self.gaes** is the placeholder for generalized advantage estimator.
You can see equation (11) in [ppo paper](https://arxiv.org/pdf/1707.06347.pdf) for detail explanation of generalized advantage estimator.
In my program, gaes are calculated with function of **self.get_gaes**.  
This function is called from the run_ppo.py,  and returned results are feeded into **self.gaes** for training.

**Comment by shamanez** [comment]
Thanks a lot
