### ISSUE TITLE
gaes = (gaes - gaes.mean()) / gaes.std()

### ISSUE THREAD

**Issue by Joll123** [uidilr/gail_ppo_tf#22]
What does this formula mean in ppo? Thanks

**Comment by uidilr** [comment]
I can't remember clearly, but I think it is for stability.
Similar question and answer is found in the link below.
Hope it answers your question!

https://datascience.stackexchange.com/questions/20098/why-do-we-normalize-the-discounted-rewards-when-doing-policy-gradient-reinforcem
