### ISSUE TITLE
About the critic network optimisation ? 

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#3]
I am talking about this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/algo/ppo.py#L70). If I am correct this is the total loss according to PPO. How to optimize the critic network, which is the value function neural network?

**Comment by uidilr** [comment]
Thanks for asking.

This [optimizer](https://github.com/uidilr/gail_ppo_tf/blob/1100f64fff6f2aa6f0889c8e65bf592904d5d92f/algo/ppo.py#L77) updates parameters of the value function and the policy function.
I did not separate optimizer between value and policy function.

**Comment by shamanez** [comment]
Ok thanks.
