### ISSUE TITLE
About the old an new policy ?

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#4]
What is happening 
In this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/run_ppo.py#L88)  ??

After this when we run the training graph by feeding obs into placeholders what happen to old policy? does it use assigned parameters or it use previously initialized parameters? I think it uses previously initialized params  that happening in this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/run_ppo.py#L30) . Any way why you need to run assign op before training op ?

**Comment by uidilr** [comment]
Hi. 
When we run the training graph by feeding obs into placeholders, old policy uses assigned parameters.

This  [line](https://github.com/uidilr/gail_ppo_tf/blob/master/run_ppo.py#L88)  assigns parameters of new policy to parameters of old policy.
Called function is [this](https://github.com/uidilr/gail_ppo_tf/blob/1100f64fff6f2aa6f0889c8e65bf592904d5d92f/algo/ppo.py#L97), and assign ops are created in [here](https://github.com/uidilr/gail_ppo_tf/blob/1100f64fff6f2aa6f0889c8e65bf592904d5d92f/algo/ppo.py#L24-L27).
