### ISSUE TITLE
What is "temp" value used in getting the output of policy network ?

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#7]
in this [line](https://github.com/uidilr/gail_ppo_tf/blob/master/network_models/policy_net.py#L5) you have used is to get **self.act_probs** by dividing the fully connected layer inputs by temp value.

**Comment by uidilr** [comment]
Hi, @shamanez.
Thanks for pointed it out! I removed it because it is unnecessary.
